language: node_js

node_js:
  - "6"

services:
  - couchdb
  - docker

env:
  - GOPATH=${TRAVIS_BUILD_DIR}/_workspace

hosts:
    - alice.cozy.local
    - bob.cozy.local
    - charlie.cozy.local

before_script:
  # setup couchdb 2 (docker)
  - docker run -d -p 5984:5984 --name couch klaemo/couchdb:2.0.0
  - sleep 10
  - curl -X PUT http://127.0.0.1:5984/{_users,_replicator,_global_changes}
  # go 1.7
  - eval "$(gimme 1.7)"
  # start a stack v3 instance from master (listening on 8080)
  - mkdir $GOPATH
  - go get -u github.com/cozy/cozy-stack
  - $GOPATH/bin/cozy-stack instances add dev
  - $GOPATH/bin/cozy-stack serve &
  # start a stack v2 from NPM (listening on 9104 & 9101)
  - npm install -g coffee-script
  - npm install cozy-data-system cozy-proxy
  - NODE_ENV=test NAME=datasystem TOKEN=token npm explore cozy-data-system npm run start &
  - sleep 3
  - NODE_ENV=test NAME=proxy TOKEN=token npm explore cozy-proxy npm run start &
  - sleep 3
  - npm explore cozy-data-system coffee commands.coffee test-install client-js ../../test/package.json
  - export NAME=client-js
  - export TOKEN=apptoken
